# Header
menu:
  首页: /
logo: https://qiniu.miiiku.xyz/src/images/logo.png
banner: https://qiniu.miiiku.xyz/src/images/banner.jpg
# banner: css/images/banner.jpg

# large cover
# long: [article, link]
# short: [category, tag]
large_legnth:
  long: 20
  short: 5

# 一言
# docs: https://hitokoto.cn/api
# type: [a, b, c, d, e, f, g]
hitokoto:
  enable: true
  type: a

# valine 评论
# docs: https://valine.js.org
# You can get your appid and appkey from https://leancloud.cn
valine:
  enable: true
  appId: 
  appKey: 
  avatar: mm
  placeholder: 随便说点什么叭～
  notify: true
  visitor: true
  pageSize: 10

disqus:
  enable: true
  website: 
  error: 如果你看不到评论，那么就真的看不到评论 w(゜Д゜)w

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# waterfall 瀑布流
# docs: https://github.com/miiiku/waterfall
# Specific configuration information go to `layout/plug-in/waterfall.ejs`
waterfall:
  enable: true


# widget behavior
archive_type: 'monthly'
show_count: false

# beian
beian: 

# Miscellaneous
google_analytics: 
gauges_analytics: 
baidu_analytics: 
tencent_analytics: 
favicon: /favicon.ico

permalink: false